### PR TITLE
Fix ruby 3 comatibility

### LINKED ISSUE #88: Errors in Ruby 3.0.x and warnings in Ruby 2.7.x
## Problem

The gem seems to use deprecated and obsolete method calls on the `URI` module. 

## Reproduction code

Run this code in Ruby 2.7.3 or Ruby 3.0.1

```ruby
require 'wikipedia'
page = Wikipedia.find 'Getting Things Done'
```
## Actual behavior

**Ruby 2.7.3** - `URI.escape is obsolete` (warning)

```
.../gems/2.7.0/gems/wikipedia-client-1.12.0/lib/wikipedia/client.rb:109: warning: URI.escape is obsolete
```

**Ruby 3.0.1** - `undefined method encode for URI:Module (NoMethodError)` (fatal)

```
.../gems/3.0.0/gems/wikipedia-client-1.12.0/lib/wikipedia/client.rb:109:in `encode': undefined method `encode' for URI:Module (NoMethodError)
```

---

I see this was mentioned in https://github.com/kenpratt/wikipedia-client/commit/b9e4b4a19aa1c18b03b0b114fdcc062fae698635 but then reverted in https://github.com/kenpratt/wikipedia-client/commit/0adc083e558e55f81606949c7d53720786ef90a5 - which I believe was the right call, since `CGI.escape` is not a 1-to-1 replacement, but the problem still needs fixing.

### PR DESCRIPTION
**Pull request by DannyBen**
This PR replaces calls for `URI.encode` and `URI.decode`, which are removed in Ruby 3.

- We are using the `addressable` gem.
- The `jeweler` dependency had to be upgraded, since it depends on an older version of `addressable`.
- The bundle was updated to the latest available dependency versions (but there are many dev dependencies that hold everything back - this needs to be addressed in a future PR).
- The `s.has_rdoc = true` was removed from the gemspec, as it is no longer supported.
- Tests seem to pass, but Rubocop screams for reasons outside the scope of this PR.

Closes #88, cc #84

### CODE REVIEW

File: lib/wikipedia/client.rb [hunk 1]
```diff
@@ -106,7 +108,7 @@ def urlify_value( val )
     def encode( val )
       case val
       when String
-        URI.encode( val, /#{URI::UNSAFE}|[\+&]/ )
+        CGI.escape(val)
```
Comment (kenpratt) [inline lib/wikipedia/client.rb:111]: How do you feel about making this `Addressable::URI.encode`? Seems like `CGI.escape` isn't a drop-in replacement, and it's quite possible that this could cause regressions. The test suite for this library is not very comprehensive. But if think this approach is likely safe, I'm not opposed.

File: Gemfile.lock [hunk 2]
```diff
@@ -17,56 +19,56 @@ GEM
       multipart-post (>= 1.2, < 3)
     git (1.8.1)
       rchardet (~> 1.8)
-    github_api (0.16.0)
-      addressable (~> 2.4.0)
-      descendants_tracker (~> 0.0.4)
+    github_api (0.11.3)
```
Comment (kenpratt) [inline Gemfile.lock:22]: Why the `github_api` downgrade here?

File: Gemfile.lock [hunk 3]
```diff
@@ -17,56 +19,56 @@ GEM
...
-      mime-types (>= 1.16, < 3.0)
-      oauth2 (~> 1.0)
+      hashie (>= 1.2)
+      multi_json (>= 1.7.5, < 2.0)
+      nokogiri (~> 1.6.0)
+      oauth2
     hashie (4.1.0)
     highline (2.0.3)
-    jeweler (2.3.9)
+    jeweler (2.3.5)
```
Comment (kenpratt) [inline Gemfile.lock:32]: Why the `jeweler` downgrade here? In your PR comment sounded like an upgrade?

File: Gemfile.lock [hunk 4]
```diff
@@ -17,56 +19,56 @@ GEM
...
-    mime-types (2.99.3)
-    mini_portile2 (2.5.0)
+    mini_portile2 (2.1.0)
     multi_json (1.15.0)
     multi_xml (0.6.0)
     multipart-post (2.1.1)
-    nokogiri (1.11.2)
-      mini_portile2 (~> 2.5.0)
-      racc (~> 1.4)
+    nokogiri (1.6.8.1)
```
Comment (kenpratt) [inline Gemfile.lock:49]: == above, seems like a `nokogiri` downgrade?

**Review by kenpratt — CHANGES_REQUESTED** [review]
Thanks for taking a crack at this, @DannyBen! Looking good, just some minor concerns.

I guess all the new Rubocop errors must be from the rubocop upgrade. Last CI run on master was passing for all but Ruby 3.0: https://travis-ci.org/github/kenpratt/wikipedia-client/builds/765777164.

File: lib/wikipedia/client.rb (hunk 1 above)
Comment (DannyBen) [reply lib/wikipedia/client.rb:111]: Using `Addressable::URI.encode` was my first choice, but tests fail with it. Not sure if it means the tests are too specific or other reason.

File: Gemfile.lock (hunk 4 above)
Comment (DannyBen) [reply Gemfile.lock:49]: About all the `Gemfile.lock` issues. I don't know why, different bundler versions perhaps have different resolving paths.

The dependencies in this gem have issues. Gemfile.lock should not be a part of the repository, and dev dependencies should move from gemspec to Gemnfile.

I don't mind taking a stab at it as well, but thought if at all, it should be a separate PR.

Comment (kenpratt) [reply Gemfile.lock:49]: If you have time, that sounds like a very positive change.

Comment (DannyBen) [reply Gemfile.lock:49]: > If you have time, that sounds like a very positive change.

In this PR, or a separate one, after this one is merged?

File: lib/wikipedia/client.rb (hunk 1 above)
Comment (kenpratt) [reply lib/wikipedia/client.rb]: I took a look at this, comparing `URI.encode`, `CGI.escape`, and `Addressable::URI.encode`. The code as written didn't really work well with `CGI.escape`, as that would encode options that are put in the base URL as well as the query parameters.

I just pushed a commit to your branch, rewriting the way this logic works (https://github.com/kenpratt/wikipedia-client/pull/89/commits/7aa230ae8e9edcbf8d62ea6252c173eedf283829). It uses `Addressable::URI.form_encode` to encode the query params options hash, instead of building the string manually. I think this is a bit simpler. I compared the output of all URLs in the test cases using this and the previous approach -- there are some minor differences, mostly where the previous approach was not encoding all special chars in the RFC, and a few minor differences like using `+` instead of `%20`. I tried them all out against the live Wikipedia API, and both URLs resolved to the same output in all cases. So I think this change should be okay, perhaps even a minor improvement. Thoughts?

File: Gemfile.lock (hunk 4 above)
Comment (kenpratt) [reply Gemfile.lock:49]: Seems like a separate PR before this one would be best, but only if you have time & agree. I'm fine with any approach :)

File: lib/wikipedia/client.rb (hunk 1 above)
Comment (DannyBen) [reply lib/wikipedia/client.rb]: Excellent. I am hoping that we can merge a PR that is only focused on making it work in Ruby 3.x, and immediately after that, perhaps work on things like dependencies and rubocop (although personally, I do not like rubocop).

I have noticed another thing - CI is still running on the deprecated travis.org - it needs to move at least to travis.com, or perhaps to Github actions.

File: Gemfile.lock (hunk 4 above)
Comment (DannyBen) [reply Gemfile.lock:49]: a separate PR from `master` will not work on Ruby 3.x...
let me try a separate PR, but if it gets messy, we might need to merge this one first.

File: lib/wikipedia/client.rb (hunk 1 above)
Comment (kenpratt) [reply lib/wikipedia/client.rb]: Sure, all in one PR is fine. I was thinking perhaps a PR to just tackle the dependency change / removing `Gemfile.lock` first, and then the Ruby 3 upgrade. But I don't feel very strongly about it. I don't think order really matters very much until we cut a new gem release, as most people using the library would be via a gem, presumably.

RE Travis CI, I noticed that deprecation warning. Do you know much about the tradeoffs of moving to the .com version vs Github actions? I'm not very familiar with either.

Comment (DannyBen) [reply lib/wikipedia/client.rb]: > Do you know much about the tradeoffs of moving to the .com version vs Github actions?

I was a long time user of travis-ci (both .org and .com) and am now 100% on Github Actions. I love travis, they are the grand-daddy of CI, but Actions is too attractive to avoid. I can help with that (opened a separate issue already).

Comment (kenpratt) [reply lib/wikipedia/client.rb]: Got it, thanks for the context. Moving to Actions sounds good to me. If you want to give it a shot, please go ahead, otherwise I can make time to try it sometime in the next week.

File: Gemfile.lock (hunk 4 above)
Comment (kenpratt) [reply Gemfile.lock:49]: I just merged https://github.com/kenpratt/wikipedia-client/pull/90, if you want to merge/rebase on that.

**Review by kenpratt — APPROVED** [review]
Looks good, thanks for bearing with me on the changes.

**Comment by kenpratt** [comment]
I'll add a commit to fix the rubocop lint.

**Comment by kenpratt** [comment]
Build passed, including Ruby 3 and Rubocop! 🎉  https://travis-ci.org/github/kenpratt/wikipedia-client/builds/768750093

I'll merge, but wait on cutting a new gem release for now in case you want to make any further changes.

**Comment by DannyBen** [comment]
> I'll merge, but wait on cutting a new gem release for now in case you want to make any further changes.

Excellent!

Lets also do the Github Actions - give me a few minutes, hopefully I wont need more than that.
